# These are supported funding model platforms

github: Toomas
patreon: Toomas 
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/cordova-apple-wallet
community_bridge: Cordova Apple Wallet
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: "https://paypal.me/enigmalabs?locale.x=en_US"
